import test from 'node:test';import assert from 'node:assert/strict';import {validateTune,scanDraft} from '../backend/validation.js';import {api} from '../backend/api.js';import {Timeline} from '../src/audio/timeline.js';
const draft=()=>scanDraft({title:'Test chart',key:'C',timeSignature:'4/4',bars:[{chords:['C'],notes:[{midi:60,duration:.5},{midi:62,duration:.5,uncertain:true},{midi:64,duration:3}]}]},'11111111-1111-4111-8111-111111111111');
test('scan validation preserves eighth notes and uncertainty without inventing rhythm',()=>{const tune=draft();assert.equal(tune.sections.A.melody[0][1].beat,.5);assert.equal(tune.sections.A.melody[0][1].uncertain,true);assert.throws(()=>scanDraft({bars:[{notes:[{midi:60,duration:1}]}]},'x'),/rhythms/);});
test('cloud validation rejects unsafe IDs, invalid pitches and incomplete bars',()=>{const tune=draft();assert.throws(()=>validateTune({...tune,slug:'../foo'}));tune.sections.A.melody[0][0].midi=100;assert.throws(()=>validateTune(tune),/pitch/);});
test('cloud endpoints require a library credential and reject cross-origin writes',async()=>{const env={DB:{}};const denied=await api(new Request('https://example.com/api/library'),env);assert.equal(denied.status,401);const cross=await api(new Request('https://example.com/api/libraries',{method:'POST',headers:{Origin:'https://evil.test'}}),env);assert.equal(cross.status,403);});
test('playback schedules scanned melody between quarter beats',()=>{const clock=new Timeline(draft(),{startTime:0});assert.equal(clock.next().beat,0);assert.equal(clock.next().beat,.5);assert.equal(clock.next().beat,1);});

test('unclear rhythm survives as a review draft but cannot be saved as a playable tune',()=>{const value={title:'Unclear bar',bars:[{chords:['C'],notes:[{midi:60,duration:1}]}]};const review=scanDraft(value,'11111111-1111-4111-8111-111111111111',{allowReview:true});assert.equal(review.sections.A.melody[0][0].duration,1);assert.equal(review.sections.A.melody[0][0].uncertain,true);assert.throws(()=>validateTune(review),/fill bar/);});

test('disabled scanner never calls an inference service',async()=>{const {transcribe}=await import('../backend/scan-worker.js');let called=false;await assert.rejects(transcribe({SCAN_ENABLED:'false',AI:{run(){called=true;}}},new Uint8Array(),'image/jpeg','test'),/paused/);assert.equal(called,false);});

test('scanner status reports paused despite a queue binding',async()=>{const response=await api(new Request('https://example.com/api/health'),{DB:{},SCAN_JOBS:{},SCAN_ENABLED:'false'});assert.equal((await response.json()).scanner,false);});
test('additional library keys resolve the same existing library',async()=>{let sql='';const env={DB:{prepare(q){sql=q;return {bind(){return {first:async()=>({id:'existing',settings:'{}'}),all:async()=>({results:[]})}}}}}};const response=await api(new Request('https://example.com/api/library',{headers:{Authorization:'Bearer '+'a'.repeat(64)}}),env);assert.equal(response.status,200);assert.deepEqual(await response.json(),{songs:[],settings:{}});});

test('single-source mode reads the same catalog without creating a browser library',async()=>{const queries=[];const env={PERSONAL_LIBRARY_ID:'only-library',DB:{prepare(sql){queries.push(sql);return {bind(...params){return {first:async()=>({id:'only-library',settings:'{}'}),all:async()=>({results:[{data:JSON.stringify({slug:'custom-one',title:'One song'})}]})}}}}}};const response=await api(new Request('https://example.com/api/library'),env);assert.equal(response.status,200);assert.equal((await response.json()).songs[0].title,'One song');assert.ok(queries[0].includes('WHERE id=?'));assert.ok(queries.every(q=>!q.includes('INSERT')));});
test('single-source mode does not expose chart photos anonymously',async()=>{const env={PERSONAL_LIBRARY_ID:'only-library',DB:{prepare(){return {bind(){return {first:async()=>({id:'only-library',settings:'{}'})}}}}}};const response=await api(new Request('https://example.com/api/scans'),env);assert.equal(response.status,410);});

test('removed scanning routes never access storage or inference',async()=>{for(const path of ['scans','scans/11111111-1111-4111-8111-111111111111/retry','scans/11111111-1111-4111-8111-111111111111/photo'])for(const method of ['GET','POST']){const response=await api(new Request('https://example.com/api/'+path,{method}),{});assert.equal(response.status,410);}});
