CREATE TABLE IF NOT EXISTS libraries (id TEXT PRIMARY KEY, key_hash TEXT NOT NULL UNIQUE, settings TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS songs (library_id TEXT NOT NULL REFERENCES libraries(id), slug TEXT NOT NULL, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(library_id, slug));
CREATE TABLE IF NOT EXISTS scans (id TEXT PRIMARY KEY, library_id TEXT NOT NULL REFERENCES libraries(id), object_key TEXT NOT NULL, status TEXT NOT NULL, draft TEXT, error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS scans_library ON scans(library_id,created_at);
CREATE TABLE IF NOT EXISTS limits (id TEXT PRIMARY KEY, count INTEGER NOT NULL);
